### ISSUE TITLE
Basic data import from CSV

### ISSUE THREAD

**Issue by alesha2911** [dimti/elvenar-calcuator-backend#1]

**Comment by dimti** [comment]
@alesha2911 Я тут подумал и решил что импорт не нужен. Можно забить исходные данные вручную. У меня есть excel-ка, но она не подходит под структуру БД и эту ексельку надо чуть менее чем полностью перерабатывать тоже вручную, а какой смысл это делать, когда уже проще переработать данные сразу в админку.
